name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable

      - name: Get dependencies
        working-directory: FertilizerCalc/FertilizerCalc
        run: flutter pub get

      - name: Generate Launcher Icons
        working-directory: FertilizerCalc/FertilizerCalc
        run: dart run flutter_launcher_icons

      - name: Generate Black Splash Screen
        working-directory: FertilizerCalc/FertilizerCalc
        run: dart run flutter_native_splash:create

      - name: Build APK
        working-directory: FertilizerCalc/FertilizerCalc
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FertilizerCalc-APK
          path: FertilizerCalc/FertilizerCalc/build/app/outputs/flutter-apk/app-release.apk
